#define DO_FIREX true
#define USE_TANK_STAND_SERVOS false

//#define ENABLE_DEBUG`

//IN MILLISECONDS. IF YOU SET IT IN SECONDS, MINUTES, HOURS, ETC, YOU WILL HAVE A BAD TIME!
#define COLD_FIREX_TIME_DEFAULT 30 * 60 * 1000 //30 minutes
#define HOT_FIREX_TIME_DEFAULT 120 * 1000 //120 seconds

#define FIREX_BOX_NUM '3' //must be an ASCII char, e.g. '2'

#define FIREX_PIN_NUM 35
#define FIREX_DUMP_PIN_NUM 32

#define BANG_BANG_BOX_NUM '3'

#define NO2_VENT_PIN_NUM {33}
#define IPA_VENT_PIN_NUM {30}
#define NO2_PRESS_PIN_NUM {32}
#define IPA_PRESS_PIN_NUM {23}

#define IPA_SENSOR_PIN_NUM {21}
#define NO2_SENSOR_PIN_NUM {33}

#define OX_PRESS_LOWER_BOUND_PSI 750
#define OX_PRESS_UPPER_BOUND_PSI 800
#define OX_OPEN_VENT_BOUND_PSI 1000
#define OX_CLOSE_VENT_BOUND_PSI 900

#define FUEL_PRESS_LOWER_BOUND_PSI 750
#define FUEL_PRESS_UPPER_BOUND_PSI 780
#define FUEL_OPEN_VENT_BOUND_PSI 850
#define FUEL_CLOSE_VENT_BOUND_PSI 825

#define MOTE1_INITIALLY_POWERED_SOLENOIDS {}
#define MOTE2_INITIALLY_POWERED_SOLENOIDS {34, 35}
#define MOTE3_INITIALLY_POWERED_SOLENOIDS {33}  